version: "1.0"

services:
  namenode:
    image: sequenceiq/hadoop-docker  
    hostname: namenode
    ports:
      - "50070:50070"
      - "8088:8088"
    environment:
      HADOOP_NAMENODE_FORMAT: "true" 
    volumes:
      - hadoop-namenode:/hadoop/hdfs/namenode  

  datanode1:
    image: sequenceiq/hadoop-docker 
    hostname: datanode1
    volumes:
      - hadoop-datanode1:/hadoop/hdfs/datanode

  datanode2:
    image: sequenceiq/hadoop-docker  
    hostname: datanode2
    volumes:
      - hadoop-datanode2:/hadoop/hdfs/datanode

  datanode3:
    image: sequenceiq/hadoop-docker  
    hostname: datanode3
    volumes:
      - hadoop-datanode3:/hadoop/hdfs/datanode

volumes:
  hadoop-namenode: {}
  hadoop-datanode1: {}
  hadoop-datanode2: {}
  hadoop-datanode3: {}

